# This workflow is for a project that using curly-eureka sdk
name: Build mod on curly-eureka

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
env:
  CE64_INCL: '${{github.workspace}}/sdk/CURLY-EUREKA-INCL.cmake'
  
jobs:
  main:
    runs-on: windows-latest
    steps:
    
    - name: This repo
      uses: actions/checkout@v3
      
    - name: Repo of curly-eureka-64x
      uses: actions/checkout@v3
      with: 
       repository: 'user95401/curly-eureka-x64'
       path: 'sdk'
       
    - name: Configure cmake
      run: cmake -B build -A x64
      
    - name: Build
      run: cmake --build build --config Release
      
    - uses: actions/upload-artifact@v4
      with:
       name: "built dlls"
       path: "**/*.dll"
